### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [maksprotsyk/homework#1]
Чи Ви пересвідчилися що Instagram API буде надавати Вам ті дані що потрібно і в потрібному обсязі? Чіткості в описі мало. На основі яких даних Ви будете обчислювати рекомендації?
Тема: Аналіз профілів соціальної мережі Instagram для розроблення рекомендаційної системи.
Виконуєте командою.

**Comment by maksprotsyk** [comment]
Ми збираємось обчислювати рекомендації на основі підписок та вподобаних дописів користувача і вже пересвідчились, що ці дані API видає без проблем, оскільки користувач Instagram не може мати більше 7500 підписок, а це ще посильне число. Далі ми плануємо використовувати для отриманих даних бібліотеку requests, що дозволить нам обробити цих користувачів без обмежень з боку API. Ми будемо аналізувати тексти дописів за допомогою бібліотеки nltk та TextBlob. Знайшовши в текстах дописів ключові слова, а також теги, ми будемо визначати тематики, які полюбляє користувач і шукати профілі за подібними тегами та тематиками.

**Comment by anrom7** [comment]
Якщо шукати ключові слова це одне звдання. Якщо визначати тематику допису це друге завдання.  Якщо шукати подібні дописи то це окреме завдання класифікації чи кластеризації. Якщо визначати тематику за ключовими словами то якість не буде високою.

**Comment by maksprotsyk** [comment]
Тоді, напевно, тематику будемо визначити з допомогою машинного навчання. Першочергово, оберемо набір основних тематик за якими будемо сортувати тексти і знайдемо бази даних таких текстів за кожною тематикою на kaggle.com або інших сайтах. Після визначення тематик дописів, що зустрічаються в підписках і дослідження того, які тематики найбільше полюбляє користувач (по частоті профілів з великою кількістю дописів даних тематик), ми будемо шукати популярні профілі за тегами, що часто зустрічаються серед підписок і серед них шукати профілі, які містять в більшості дописи з тематик, які подобаються користувачу.
